export const QUESTION_LIST_REQUEST = 'QUESTION_LIST_REQUEST'
export const QUESTION_LIST_SUCCESS = 'QUESTION_LIST_SUCCESS'
export const QUESTION_LIST_FAIL = 'QUESTION_LIST_FAIL'
export const QUESTION_LIST_RESET = 'QUESTION_LIST_RESET'

export const QUESTION_ANSWERED_REQUEST = 'QUESTION_ANSWERED_REQUEST'
export const QUESTION_ANSWERED_SUCCESS = 'QUESTION_ANSWERED_SUCCESS'
export const QUESTION_ANSWERED_FAIL = 'QUESTION_ANSWERED_FAIL'

export const SAVE_QUESTION_REQUEST = 'SAVE_QUESTION_REQUEST'
export const SAVE_QUESTION_SUCCESS = 'SAVE_QUESTION_SUCCESS'
export const SAVE_QUESTION_FAIL = 'SAVE_QUESTION_FAIL'


export const NEW_QUESTION_REQUEST = 'NEW_QUESTION_REQUEST'
export const NEW_QUESTION_SUCCESS = 'NEW_QUESTION_SUCCESS'
export const NEW_QUESTION_FAIL = 'NEW_QUESTION_FAIL'